### ISSUE TITLE
Fail on initial test

### ISSUE THREAD

**Issue by jolynyc** [dylanhthomas/peat-media-converter#9]
I gave it a test, and got a fail. This is mediainfo on the converted video

General
Complete name                            : D:\!!!!templates\!!!isoc\Core Pack\Logo\STINGS\converter_output\siumulcast_converted.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format profile                           : OpenDML
Format settings                          : BitmapInfoHeader
File size                                : 2.04 GiB
Duration                                 : 7 s 40 ms
Overall bit rate                         : 2 488 Mb/s
Frame rate                               : 25.000 FPS
Writing application                      : Lavf59.17.102

Video
ID                                       : 0
Format                                   : YUV
Codec ID                                 : I420
Codec ID/Info                            : 8 bit Y plane followed by 8 bit 2x2 subsampled U and V planes.
Duration                                 : 7 s 40 ms
Bit rate                                 : 2 488 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Scan type                                : Progressive
Compression mode                         : Lossless
Bits/(Pixel*Frame)                       : 12.000
Stream size                              : 2.04 GiB (100%)

To which PEAT responded "Can't Convert video stream". Choking on the 4K frame size?

**Comment by dylanhthomas** [comment]
@jolynyc Any chance you can send me a link to download the video and do some local testing?

**Comment by dylanhthomas** [comment]
@jolynyc It's odd, I was able to convert using both "Basic Processing" and "Full Processing" without issue, but I've come across issues in the past that were caused by different under-the-hood Windows configurations.

Couple of questions:

- Are those actual exclamation points in your file path?

- What version of Windows are you using?

- What version does your app say? (Help > About).  Latest is 1.0.4
![image](https://github.com/user-attachments/assets/a33ff8fb-569d-4c66-9d4e-519dd3d745f1)

**Comment by jolynyc** [comment]
1.0.4

![image](https://github.com/user-attachments/assets/064114b9-0884-48b2-b5fd-ac3a707529fb)

I am on Windows 10, and yes I use exclamation marks to give folders priority in alphanumeric listing. Has never been an issue.

**Comment by jolynyc** [comment]
And to be clear, I can do the conversion fine with the result as shown in mediaInfo above, but Trace Center Photosensitive Epilepsy Analysis Tool (PEAT) Version 1.6 does not accept the result.

**Comment by dylanhthomas** [comment]
Ahh, the problem is with PEAT.  I misunderstood.

Here are my results testing the converted files:

"Basic"-
file did not work...it's over PEATs 2GB-ish file limit.
![image](https://github.com/user-attachments/assets/f827b27e-70f6-4fea-b005-9f9dd9b06246)

"Full" -
file worked (60mb down-sampled to 640px)
![image](https://github.com/user-attachments/assets/ef049629-bdcf-4cc2-a114-dac04d94234b)

**Comment by dylanhthomas** [comment]
It's not so much frame size as file size. The limit depends somewhat on PEAT and somewhat on the system you're using.  In my experience 1GB and smaller files always work. Above 1GB is hit or miss.

Part of the "Full" processing is downsampling the files to 640px, and if the file is bigger than 1GB, splitting the file into less than 1GB chunks.

Let me know if the Full processed file works for you.  If not, there is something else we need to figure out.

Thanks =)

**Comment by jolynyc** [comment]
Yes, it doesn't say anything about an input file size limit. I assumed it
would be resized to make it fit. Was surprised when it came out unchnaged
at 4K.

**Comment by dylanhthomas** [comment]
Yeah, that's the basic vs full. There has been some confusion about it, so I think I need to do a better job describing the purposes. I also have an enhancement ticket to check if the output is over 1GB and set an alert.

If there is anything else, please let me know =)

**Comment by jolynyc** [comment]
Since output is a function of input, maybe a check on the input size on
basic, with a choice to auto fall over to full?
